spring.application.name=NeonArkCreaturManagementSystem

spring.datasource.url=jdbc:postgresql://localhost:5547/creature_management
spring.datasource.username=neonark
spring.datasource.password=neonarkpass

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true